version: '3.8'
services:
  mediasoup-loadbalancer:
    image: nginx:1.19.3-alpine
    container_name: mediasoup-loadbalancer_test
    working_dir: /etc/nginx/conf.d/
    ports:
      - '9990:80'
    volumes:
      - ./.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    tty: true
