version: '3.8'
services:
  sfu-frontend-demo.pro:
    container_name: sfu-frontend-demo.pro
    image: 'sfufrontend'
    working_dir: /home/frontend
    command: bash -c "yarn && yarn pro"
    stdin_open: true
    tty: true
    ports:
      - '${PORT_PRO}:${PORT_PRO}/tcp'
      - '${PORT_PRO}:${PORT_PRO}/udp'
    volumes:
      - .:/home/frontend
  sfu-frontend-demo.dev:
    container_name: sfu-frontend-demo.dev
    image: 'sfufrontend'
    working_dir: /home/frontend
    command: bash -c "yarn && yarn dev"
    stdin_open: true
    tty: true
    ports:
      - '${PORT_DEV}:${PORT_DEV}/tcp'
      - '${PORT_DEV}:${PORT_DEV}/udp'
    volumes:
      - .:/home/frontend
  sfu-frontend-demo.dev2:
    container_name: sfu-frontend-demo.dev2
    image: 'sfufrontend'
    working_dir: /home/frontend
    command: bash -c "yarn && yarn dev2"
    stdin_open: true
    tty: true
    ports:
      - '${PORT_DEV_2}:${PORT_DEV_2}/tcp'
      - '${PORT_DEV_2}:${PORT_DEV_2}/udp'
    volumes:
      - .:/home/frontend
