version: '3.8'
services:
  sfusignal.pro:
    container_name: sfu-signal
    image: 'sfusignal'
    working_dir: /home/signal
    command: bash -c "yarn && yarn devtest"
    stdin_open: true
    tty: true
    ports:
      - '${PORT}:${PORT}/tcp'
      - '${PORT}:${PORT}/udp'
    environment:
      - LIMIT=${LIMIT}
      - REDIS_HOST=${REDIS_HOST}
      - PORT=${PORT}
    volumes:
      - .:/home/signal
