version: '3.8'
services:
  sfusignal.external.test:
    container_name: sfusignal.external.test
    image: 'sfusignal'
    working_dir: /home/signal
    command: bash -c "yarn && yarn start"
    stdin_open: true
    tty: true
    networks:
      signal_tuple_networks:
        ipv4_address: 172.28.1.2
    ports:
      - '${PORT}:${PORT}/tcp'
      - '${PORT}:${PORT}/udp'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - PORT=${PORT}
      - CRYPTO_KEY=${CRYPTO_KEY}
    volumes:
      - .:/home/signal

networks:
  signal_tuple_networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.1.1
