version: '3.8'
services:
  sfusignal_1:
    container_name: sfusignal_1
    image: 34.81.83.64:3100/webrtc/mediasoup-signaling-server
    # working_dir: /home/signal
    # command: bash -c "yarn && yarn start"
    stdin_open: true
    tty: true
    networks:
      signal_tuple_networks:
        ipv4_address: 172.28.1.2
    ports:
      - '${PORT_1}:${PORT_1}/tcp'
      - '${PORT_1}:${PORT_1}/udp'
    environment:
      - REDIS_HOST=${REDIS_HOST_1}
      - REDIS_DB_INDEX=${REDIS_DB_INDEX}
      - PORT=${PORT_1}
      - CRYPTO_KEY=${CRYPTO_KEY_1}
    # volumes:
    #   - .:/home/signal
  # sfusignal_2:
  #   container_name: sfusignal_2
  #   image: 'sfusignal'
  #   working_dir: /home/signal
  #   command: bash -c "yarn && yarn start"
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     signal_tuple_networks:
  #       ipv4_address: 172.28.1.4
  #   ports:
  #     - '${PORT_2}:${PORT_2}/tcp'
  #     - '${PORT_2}:${PORT_2}/udp'
  #   environment:
  #     - REDIS_HOST=${REDIS_HOST_2}
  #     - REDIS_DB_INDEX=${REDIS_DB_INDEX}
  #     - PORT=${PORT_2}
  #     - CRYPTO_KEY=${CRYPTO_KEY_2}
  #   volumes:
  #     - .:/home/signal

networks:
  signal_tuple_networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.1.1
