version: '3.8'

services:
  webrtcapp:
    image: sfuserver
    container_name: sfu1
    working_dir: /home/mediasoup
    ports:
      - '${PORT}:${PORT}/tcp'
      - '${PORT}:${PORT}/udp'
      - '${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/udp'
      - '${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/tcp'
    environment:
      - DOMAIN=${IP}
      - PORT=${PORT}
      - MEDIASOUP_LISTEN_IP=${IP}
      - MEDIASOUP_ANNOUNCED_IP=${IP}
      - MEDIASOUP_MIN_PORT=${MIN_PORT}
      - MEDIASOUP_MAX_PORT=${MAX_PORT}
    volumes:
      - .:/home/mediasoup
    stdin_open: true
    tty: true
    command: bash -c "npm install && npm run dev"
