version: "3.8"

services:
  webrtcsfudev1:
    image: sfuserver
    container_name: ${CONTAINER_NAME}
    working_dir: /home/mediasoup
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${PORT}:${PORT}/udp"
      - "${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/udp"
      - "${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/tcp"
    environment:
      - DOMAIN=${DOMAIN}
      - PORT=${PORT}
      - MEDIASOUP_LISTEN_IP=${IP}
      - MEDIASOUP_ANNOUNCED_IP=${ANNOUNCE_IP}
      - MEDIASOUP_MIN_PORT=${MIN_PORT}
      - MEDIASOUP_MAX_PORT=${MAX_PORT}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - ./src:/home/mediasoup/src
      - ./config.ts:/home/mediasoup/config.ts
      - ./index.ts:/home/mediasoup/index.ts
    stdin_open: true
    tty: true
    command: bash -c "npm run start"
  webrtcsfudev2:
    image: sfuserver
    container_name: ${CONTAINER_NAME_2}
    working_dir: /home/mediasoup
    ports:
      - "${PORT_2}:${PORT_2}/tcp"
      - "${PORT_2}:${PORT_2}/udp"
      - "${MIN_PORT_2}-${MAX_PORT_2}:${MIN_PORT_2}-${MAX_PORT_2}/udp"
      - "${MIN_PORT_2}-${MAX_PORT_2}:${MIN_PORT_2}-${MAX_PORT_2}/tcp"
    environment:
      - DOMAIN=${DOMAIN_2}
      - PORT=${PORT_2}
      - MEDIASOUP_LISTEN_IP=${IP_2}
      - MEDIASOUP_ANNOUNCED_IP=${ANNOUNCE_IP_2}
      - MEDIASOUP_MIN_PORT=${MIN_PORT_2}
      - MEDIASOUP_MAX_PORT=${MAX_PORT_2}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - ./src:/home/mediasoup/src
      - ./config.ts:/home/mediasoup/config.ts
      - ./index.ts:/home/mediasoup/index.ts
    stdin_open: true
    tty: true
    command: bash -c "npm run start"
