version: '3.8'

services:
  webrtcsfu1:
    image: 34.81.83.64:3100/webrtc/mediasoup-server
    container_name: ${CONTAINER_NAME}
    # working_dir: /home/mediasoup
    # networks:
    #   ithelp_application:
    #     ipv4_address: ${IP}
    ports:
      - '${PORT}:${PORT}/tcp'
      - '${PORT}:${PORT}/udp'
      - '${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/udp'
      - '${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/tcp'
    environment:
      - DOMAIN=${DOMAIN}
      - PORT=${PORT}
      - MEDIASOUP_LISTEN_IP=${IP}
      - MEDIASOUP_ANNOUNCED_IP=${ANNOUNCE_IP}
      - MEDIASOUP_MIN_PORT=${MIN_PORT}
      - MEDIASOUP_MAX_PORT=${MAX_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DB_INDEX=${REDIS_DB_INDEX}
    # volumes:
      # - .:/home/mediasoup
    # stdin_open: true
    # tty: true
    # command: bash -c "npm install && npm run start"
  webrtcsfu2:
    image: sfuserver
    container_name: ${CONTAINER_NAME_2}
    working_dir: /home/mediasoup
    # networks:
    #   ithelp_application:
    #     ipv4_address: 172.28.0.3
    ports:
      - '${PORT_2}:${PORT_2}/tcp'
      - '${PORT_2}:${PORT_2}/udp'
      - '${MIN_PORT_2}-${MAX_PORT_2}:${MIN_PORT_2}-${MAX_PORT_2}/udp'
      - '${MIN_PORT_2}-${MAX_PORT_2}:${MIN_PORT_2}-${MAX_PORT_2}/tcp'
    environment:
      - DOMAIN=${DOMAIN_2}
      - PORT=${PORT_2}
      - MEDIASOUP_LISTEN_IP=${IP_2}
      - MEDIASOUP_ANNOUNCED_IP=${ANNOUNCE_IP_2}
      - MEDIASOUP_MIN_PORT=${MIN_PORT_2}
      - MEDIASOUP_MAX_PORT=${MAX_PORT_2}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DB_INDEX=${REDIS_DB_INDEX}
    volumes:
      - .:/home/mediasoup
    stdin_open: true
    tty: true
    command: bash -c "npm run start"
# networks:
#   ithelp_application:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16
#           gateway: 172.28.0.1
