version: '3.8'
services:
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass test
    volumes:
      - redis-data:/data
volumes:
  redis-data:
