version: "3.8"
services:
  redis.dev:
    restart: always
    container_name: redis.dev
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass test
    volumes:
      - redis-dev:/data
  redis.external.test:
    restart: always
    container_name: redis.external.test
    image: redis:alpine
    ports:
      - 6378:6379
    command: redis-server --requirepass test
    volumes:
      - redis-external-test:/data
  redis.my.test:
    restart: always
    container_name: redis.my.test
    image: redis:alpine
    ports:
      - 6377:6379
    command: redis-server --requirepass test
    volumes:
      - redis-my-test:/data
volumes:
  redis-dev:
  redis-my-test:
  redis-external-test:
